# Alembic migration script template
"""Update verification event model with analytics fields

Revision ID: 9cbb6a33bf1a
Revises: 001
Create Date: 2026-01-07 18:21:55.785526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cbb6a33bf1a'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_events_pack', table_name='verification_events')
    op.drop_table('verification_events')
    op.drop_table('supply_chain_events')
    op.drop_index('ix_batches_manufacturer', table_name='batches')
    op.drop_index('ix_batches_product', table_name='batches')
    op.drop_index('ix_packs_batch', table_name='packs')
    op.drop_index('ix_packs_status', table_name='packs')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_packs_status', 'packs', ['status'], unique=False)
    op.create_index('ix_packs_batch', 'packs', ['batch_id'], unique=False)
    op.create_index('ix_batches_product', 'batches', ['product_id'], unique=False)
    op.create_index('ix_batches_manufacturer', 'batches', ['manufacturer_id'], unique=False)
    op.create_table('supply_chain_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('carton_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pack_id', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('from_organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('to_organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('location_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blockchain_tx_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], name='supply_chain_events_batch_id_fkey'),
    sa.ForeignKeyConstraint(['carton_id'], ['cartons.carton_id'], name='supply_chain_events_carton_id_fkey'),
    sa.ForeignKeyConstraint(['from_organization_id'], ['organizations.organization_id'], name='supply_chain_events_from_organization_id_fkey'),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.pack_id'], name='supply_chain_events_pack_id_fkey'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.user_id'], name='supply_chain_events_performed_by_fkey'),
    sa.ForeignKeyConstraint(['to_organization_id'], ['organizations.organization_id'], name='supply_chain_events_to_organization_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', name='supply_chain_events_pkey')
    )
    op.create_table('verification_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('pack_id', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('verified_by_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('verification_result', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('location_latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True),
    sa.Column('location_longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True),
    sa.Column('location_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('device_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.pack_id'], name='verification_events_pack_id_fkey'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.user_id'], name='verification_events_verified_by_user_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', name='verification_events_pkey')
    )
    op.create_index('ix_verification_events_pack', 'verification_events', ['pack_id'], unique=False)
    # ### end Alembic commands ###
